---
title: "Exploración Plantas Extintas"
author: "Luis Jimeno"
date: "4/6/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
library(tidyverse)
library(kableExtra)
```

## Introducción

### Plantas Extintas

Este es el texto para ver cómo colocar lo que queremos en **negrilla** o en *cursiva* o colocar [Vinculos](http://f2ponline,org) en github

[Ver Diapositivas del curso](https://derek-corcoran-barrios.github.io/Clase2/Clase2InvestigacionReproducible#25)

```{r}
plants <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-08-18/plants.csv")
actions <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-08-18/actions.csv")
threats <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-08-18/threats.csv")
```

## DATOS DE SUDAMERICA

El número de especies que son de Sudamerica es de **`r plants %>% dplyr::filter(continent == "South America") %>%  nrow()` especies**

